participants:

    Solid:
        interfaces:
        - nodes-mesh: Solid-Mesh
          patch: surface
          read-data: [Forces]
          write-data: [Displacements]
          
precice-config-file: ../precice-config.xml
